{
 "title": "Horcrux Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "chain", "label": "Chain", "query": { "query": "label_values(chain)" } },
   { "name": "share", "label": "Horcrux Share (Unused)", "query": { "query": "label_values(share)" } }
  ]
 },
 "panels": [
  { "title": "Horcrux Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consecutive Missing Threshold Shares",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "signer_missed_ephemeral_shares",
     "legendFormat": "s{{share}}/{{instance}} [X] {{peerid}}"
    }
   ]
  },
  {
   "title": "Phase 1: Leader -> Remote Lag (sec) [ Fastest Sign Phase 2, Dead Peers Do Not Update ]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "signer_cosigner_ephemeral_share_lag_seconds{chain=\"$chain\", quantile=\"0.9\"}",
     "legendFormat": "s{{share}}/{{instance}} -> {{peerid}}"
    }
   ]
  },
  {
   "title": "Consecutive Sentry Connect Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_sentry_connect_tries{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Sentry Connect Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_sentry_connect_tries{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Phase 2: Signing Cosigner Lag (sec) [ Only Updates on Peer Sign ]",
   "type": "timeseries",
   "description": "Peers slow to respond in the Ephemeral Share phase may not appear since they are not asked to sign.",
   "gridPos": { "h": 7, "w": 11, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "signer_cosigner_sign_lag_seconds{chain=\"$chain\", quantile=\"0.9\"}",
     "legendFormat": "s{{share}}/{{instance}} -> {{peerid}}"
    }
   ]
  },
  {
   "title": "Precommits Signed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_precommits_signed{chain=\"$chain\"}",
     "legendFormat": "{{share}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Prevotes Signed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_prevotes_signed{chain=\"$chain\"}",
     "legendFormat": "{{share}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Seconds Since Last Threshold-Share Sign [ Should be under 2x Blocktime ]",
   "type": "timeseries",
   "description": "Needs 1-3s scrape_interval to be accurate.\nShould not exceed 2x expected block time.",
   "gridPos": { "h": 7, "w": 11, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "signer_seconds_since_last_local_ephemeral_share_time{chain=\"$chain\"}",
     "legendFormat": "s{{share}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Proposals Signed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_proposals_signed{chain=\"$chain\"}",
     "legendFormat": "{{share}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Signed as Raft Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_raft_leader{chain=\"$chain\"}",
     "legendFormat": "{{share}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Total Missing Threshold Shares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "signer_total_missed_ephemeral_shares",
     "legendFormat": "s{{share}}/{{instance}} [X] {{peerid}}"
    }
   ]
  },
  {
   "title": "Times Forwarded to Raft Leader to Sign",
   "type": "stat",
   "description": "If your cluster signing is late AND this metric is high, it indicates your cluster may have too much internal latency and can't handle non-ideal cluster cases.  Cluster closer geograpically (or with lower latency links).  This indicates the sentry gave a raft follower the signing request so an extra step is required to forward the request onto the leader.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_raft_not_leader{chain=\"$chain\"}",
     "legendFormat": "{{share}}/{{instance}}"
    }
   ]
  },
  { "title": "Misses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Consecutive Missed Prevotes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_missed_prevotes{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consecutive Missed Precommits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "signer_missed_precommits{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Missed Precommits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "signer_total_missed_precommits{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Missed Prevotes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_missed_prevotes{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Raft Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Raft Heartbeat Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "horcrux_raft_transition_heartbeat_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Leader Lost Quorum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "horcrux_raft_transition_leader_lease_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Leader Election Timeout Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "signer_total_raft_leader_election_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft State - Become Leader Times",
   "type": "timeseries",
   "description": "run: \"hocrux elect share#\" to force a change",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    { "expr": "horcrux_raft_state_leader", "legendFormat": "{{share}} / {{instance}}" }
   ]
  },
  {
   "title": "Raft State -  Become Follower Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "targets": [
    { "expr": "horcrux_raft_state_follower", "legendFormat": "{{share}} / {{instance}}" }
   ]
  }
 ]
}