{
 "title": "Horcrux Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "chain", "label": "Chain", "query": { "query": "label_values(chain)" } }
  ]
 },
 "panels": [
  { "title": "Horcrux Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consecutive Missing Threshold Shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "signer_missed_ephemeral_shares",
     "legendFormat": "{{instance}} failed to get signature from {{peerid}}"
    }
   ]
  },
  {
   "title": "Cosigner Lag (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "signer_cosigner_sign_lag_seconds{chain=\"$chain\", quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consecutive Sentry Connect Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_sentry_connect_tries{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Sentry Connect Retries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_sentry_connect_tries{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Precommits Signed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_precommits_signed{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Missing Threshold Shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "signer_total_missed_ephemeral_shares",
     "legendFormat": "{{instance}} failed to get signature from {{peerid}}"
    }
   ]
  },
  {
   "title": "Seconds Since Last Threshold-Share Sign",
   "type": "timeseries",
   "description": "Needs 1-3s scrape_interval to be accurate.\nShould not exceed 2x expected block time.",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "signer_seconds_since_last_local_ephemeral_share_time{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prevotes Signed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_prevotes_signed{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proposals Signed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_proposals_signed{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Missed Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Consecutive Missed Prevotes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_missed_prevotes{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consecutive Missed Precommits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "signer_missed_precommits{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Missed Precommits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "signer_total_missed_precommits{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Missed Prevotes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signer_total_missed_prevotes{chain=\"$chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Raft Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Raft Heartbeat Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "horcrux_raft_transition_heartbeat_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Leader Lost Quorum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "horcrux_raft_transition_leader_lease_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Leader Election Timeout Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "signer_total_raft_leader_election_timeout",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}